export const GET_BUGS = "GET_BUGS";
export const LOGIN_SUCCESS = "LOGIN";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GET_USER_INFO = "GET_USER_INFO";
export const LOGOUT = "LOGOUT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_ALL_PROJECT_FAIL = "GET_ALL_PROJECT_FAIL";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SPECEFIC_BUGS = "GET_USER_SPECEFIC_BUGS";
export const GET_USER_SPECEFIC_BUGS_FAIL = "GET_USER_SPECEFIC_BUGS_FAIL";

export const GET_USER_SPECEFIC_CONTENTS = "GET_USER_SPECEFIC_CONTENTS";
export const GET_USER_SPECEFIC_CONTENTS_FAIL = "GET_USER_SPECEFIC_CONTENTS_FAIL";

export const ADD_FEATURE = 'ADD_FEATURE';
export const GET_ALL_FEATURES = 'GET_ALL_FEATURES';
export const GET_ALL_FEATURE_FAIL = 'GET_ALL_FEATURE_FAIL';

export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const GET_ALL_COMMENT_FAIL = 'GET_ALL_COMMENT_FAIL';

export const ADD_LIKE_QUERY = 'ADD_LIKE_QUERY';
export const ADD_LIKE_QUERY_FAIL = 'ADD_LIKE_QUERY_FAIL';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

export const GET_DASHBOARD_STATS = 'GET_DASHBOARD_STATS';
export const GET_DASHBOARD_STATS_FAIL = 'GET_DASHBOARD_STATS_FAIL';